services:
  - type: web
    name: btc-options-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DELTA_API_KEY
        sync: false
      - key: DELTA_API_SECRET
        sync: false
